# authサービスの環境変数に以下を追加してください:

      # ログレベル設定（デバッグ用）
      GOTRUE_LOG_LEVEL: ${GOTRUE_LOG_LEVEL:-info}
      GOTRUE_LOG_FORMAT: ${GOTRUE_LOG_FORMAT:-json}

      # Cookie configuration (既存の部分を以下に置き換え)
      GOTRUE_COOKIE_DOMAIN: ${GOTRUE_COOKIE_DOMAIN:-.compass-pharmacy.jp}
      GOTRUE_COOKIE_NAME: ${GOTRUE_COOKIE_NAME:-sb-db-auth-token}
      GOTRUE_COOKIE_SAMESITE: ${GOTRUE_COOKIE_SAMESITE:-lax}
      GOTRUE_COOKIE_SECURE: ${GOTRUE_COOKIE_SECURE:-true}
      GOTRUE_COOKIE_DURATION: ${GOTRUE_COOKIE_DURATION:-604800}